name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no vaidityatanwar@${{ secrets.VM_Static_Ip }} '
            cd /home/vaidityatanwar/codemelon &&
            git pull &&
            
            sudo docker-compose down || true &&  # Stop and remove any existing containers
            sudo docker-compose build &&  # Build the images if necessary
            sudo docker-compose up -d  # Start containers in detached mode
          '
